@startuml

title Specialty State Diagram

'https://plantuml.com/state-diagram

left to right direction
'top to bottom direction

scale 1200 width

[*] -> SPECIALTY_LIST: button_list_dialog(

SPECIALTY_LIST --> SPECIALTY_NEW : button_addNew_dialog()
SPECIALTY_NEW --> SPECIALTY_LIST: button_cancel_and_back()
state SPECIALTY_NEW {
    SPECIALTY_NEW --> SPECIALTY_NEW : button_addNew_perform() not OK, invalid
}
SPECIALTY_NEW -> SPECIALTY_DETAILS: button_addNew_perform() OK


SPECIALTY_LIST -> SPECIALTY_DETAILS: button_detail_dialog()
SPECIALTY_DETAILS --> SPECIALTY_LIST: button_back_to_list()

SPECIALTY_DETAILS --> SPECIALTY_EDIT: button_edit_dialog()
SPECIALTY_EDIT --> SPECIALTY_DETAILS: button_cancel_and_back()
state SPECIALTY_EDIT {
    SPECIALTY_EDIT --> SPECIALTY_EDIT: button_update_perform() not OK, invalid
}
SPECIALTY_EDIT --> SPECIALTY_DETAILS: button_update_perform() OK

SPECIALTY_DETAILS --> SPECIALTY_DELETE: button_delete_dialog()
SPECIALTY_DELETE --> SPECIALTY_DETAILS: button_acancel_and_back()
state SPECIALTY_DELETE {
    SPECIALTY_DELETE --> SPECIALTY_DELETE: button_delete_perform() not OK, invalid
}
SPECIALTY_DELETE --> SPECIALTY_DETAILS: button_delete_perform() OK

SPECIALTY_LIST -> [*]
SPECIALTY_DETAILS -> [*]

@enduml