@startuml

title Owner Use Case State Diagram without Pet and Visits

'https://plantuml.com/state-diagram

left to right direction
'top to bottom direction

scale 1200 width

[*] --> OWNER_LIST

OWNER_LIST --> OWNER_NEW : button_addNew_owner()

OWNER_NEW --> OWNER_LIST: cancel_and_back()
OWNER_NEW --> OWNER_DETAILS: owner_addNew() OK

OWNER_LIST --> OWNER_DETAILS: button_details_owner()

OWNER_DETAILS --> OWNER_LIST: button_back_to_list()

OWNER_DETAILS --> OWNER_EDIT: button_edit_owner()
OWNER_EDIT --> OWNER_DETAILS: cancel_and_back()

OWNER_DETAILS --> OWNER_DELETE: button_delete_owner()
OWNER_DELETE --> OWNER_DETAILS: cancel_and_back()

OWNER_EDIT --> OWNER_DETAILS: owner_update() OK
OWNER_DELETE --> OWNER_DETAILS: owner_delete() OK

state OWNER_DETAILS {
}

state OWNER_EDIT {
    OWNER_EDIT --> OWNER_EDIT: owner_update() not OK, invalid
}
state OWNER_DELETE {
    OWNER_DELETE --> OWNER_DELETE: owner_udelete() not OK, invalid
}
state OWNER_NEW {
    OWNER_NEW --> OWNER_NEW : owner_addNew() not OK, invalid
}

OWNER_LIST --> [*]
OWNER_DETAILS --> [*]

@enduml